spring:
  devtools:
    add-properties: false
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver

  #    url: jdbc:postgresql:postgres://eefchjwymxlowj:793173c830b09253101eee32717272dfc2ddc75702e7c85884f09b882db4f98d@ec2-52-54-212-232.compute-1.amazonaws.com:5432/d83l1brh2pch1v?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
#    driver-class-name: org.postgresql.Driver
#    driverClassName: org.postgresql.Driver
#    ssl:
#      enabled: true
#      key-store-type: org.postgresql.ssl.NonValidatingFactory
  application:
    name: phytech
#  main:
#    web-application-type: none
  jpa:
    show-sql: true
    generate-ddl: false
#    database-platform: DB2Platform
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        id:
#          optimizer:
#            pooled:
##              preferred: gov.btl.tevel.liba.core.jpa.BTLPooledLoOptimizer

server:
  port: 9080
  tomcat:
    max-connections: 20000
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100
