spring:
  devtools:
    add-properties: false
  datasource:
    password: tamar123
    username: postgres
    url: jdbc:postgresql:localhost:5432/PHYTECH:P1
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
  application:
    name: phytech
  main:
    web-application-type: none
server:
  connection-timeout: 30s
  port: 9080
  tomcat:
    max-connections: 20000
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100